# Generated by Django 4.1.6 on 2023-02-09 15:55

from django.db import migrations, models


def create_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    User.objects.create_user("admin", "admin@example.com", "admin")


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.RunPython(create_user),
    ]
